-- SQL Setup Script for Atlanta Homelessness Explorer Project
-- Target Database: PostgreSQL with PostGIS extension

-- 1. Enable PostGIS Extension (Run once per database)
-- Connect to your database (e.g., 'atl') first, then run:
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create Schema (Optional, but good practice)
-- Creates a 'demo' schema to hold the project tables.
CREATE SCHEMA IF NOT EXISTS demo;

-- 3. Create Tracts Table
-- Stores census tract boundaries. Assumes tracts data will be loaded later.
DROP TABLE IF EXISTS demo.tracts; -- Drop if exists to start fresh
CREATE TABLE demo.tracts (
    gid SERIAL PRIMARY KEY, -- Optional primary key
    geoid TEXT UNIQUE,      -- Census Tract GEOID (e.g., '13121000100'). UNIQUE constraint is good practice.
    -- Add other tract attributes if needed (e.g., ALAND, AWATER), otherwise keep simple.
    geom GEOMETRY(MultiPolygon, 4326) -- Geometry column, specify type (Polygon/MultiPolygon) and SRID (4326 for WGS84)
);

-- Create a spatial index for faster spatial queries
CREATE INDEX tracts_geom_idx ON demo.tracts USING GIST (geom);

-- 4. Create PIT Counts Table
-- Stores the simulated individual point-in-time counts with demographics.
-- Data will be loaded from the generated CSV file.
DROP TABLE IF EXISTS demo.pit_counts; -- Drop if exists to start fresh
CREATE TABLE demo.pit_counts (
    id SERIAL PRIMARY KEY, -- Simple auto-incrementing primary key
    geoid TEXT,            -- GEOID of the tract the person is associated with (references demo.tracts.geoid)
    age TEXT,              -- Age group category (e.g., '18-34')
    sex TEXT,              -- Sex category (e.g., 'Male', 'Female')
    ethnicity TEXT         -- Ethnicity category (e.g., 'Black', 'White')
    -- Add FOREIGN KEY constraint if desired, requires geoid in tracts to be PRIMARY KEY or UNIQUE
    -- CONSTRAINT fk_tract FOREIGN KEY(geoid) REFERENCES demo.tracts(geoid)
);

-- Create an index on geoid for faster joins if needed
CREATE INDEX pit_counts_geoid_idx ON demo.pit_counts (geoid);


-- --- Instructions after running this script ---
-- 1. Load Tract Data: Use a tool like 'shp2pgsql' or 'ogr2ogr' to load your
--    tract shapefile/geojson (e.g., 'atl_tracts.geojson') into the 'demo.tracts' table.
--    Ensure the geometry is loaded into the 'geom' column with SRID 4326.
--    Example using ogr2ogr (requires GDAL):
--    ogr2ogr -f "PostgreSQL" PG:"dbname='atl' host='localhost' user='postgres' password='your_password'" \
--            "data/atl_tracts.geojson" -nln demo.tracts -nlt PROMOTE_TO_MULTI \
--            -lco GEOMETRY_NAME=geom -lco SCHEMA=demo -lco OVERWRITE=YES \
--            -t_srs EPSG:4326 -select "GEOID" -- Add other fields if needed

-- 2. Load PIT Counts Data: Use the psql '\copy' command or another import tool
--    to load the 'data/pit_counts_individuals.csv' file generated by the simulation
--    script into the 'demo.pit_counts' table.
--    Example using psql:
--    \copy demo.pit_counts (geoid, age, sex, ethnicity) FROM '/path/to/your/hotspot_atl/data/pit_counts_individuals.csv' WITH (FORMAT CSV, HEADER);

-- Grant necessary privileges if your web app user is different from the loading user
-- GRANT USAGE ON SCHEMA demo TO your_webapp_user;
-- GRANT SELECT ON demo.tracts TO your_webapp_user;
-- GRANT SELECT ON demo.pit_counts TO your_webapp_user;

\echo "Setup script finished. Remember to load data into the tables."


